---
title: "TAV Torino-Lione | Articoli"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```
### Accademia della Crusca
* **02/11/2015** [Il TAV e la TAV](http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/tav-tav)

### AGI
* **25/07/2019** [TAV: LA VERITÀ DEI FATTI | Un super fact-checking in 35 domande e risposte sul più importante progetto infrastrutturale in Italia](https://www.agi.it/saperetutto/tav_torino_lione_costi_effetti-4451507/longform/2018-10-12/)

### Avvenire
* **02/02/2019** [Andrea Boitani: «Per la Tav tre scenari, nessuno a costo zero»](https://www.avvenire.it/attualita/pagine/andrea-boitani-tav)

### behavioraleconomics.com
* [Action bias](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/action-bias/)
* [Cognitive bias](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/cognitive-bias/)
* [Heuristic](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/heuristic/)
* [Optimism bias](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/optimism-bias/)
* [Sunk cost fallacy](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/sunk-cost-fallacy/)
* [Utility](https://www.behavioraleconomics.com/resources/mini-encyclopedia-of-be/utility/)

### Corriere della Sera 
* **26/06/2019** [Ponti: «Sulla Tav Toninelli è come Delrio e il Pd. La mia analisi mai applicata, usata solo per fini politici»](https://www.corriere.it/politica/19_giugno_26/ponti-sulla-tav-toninelli-come-delrio-pd-mia-analisi-mai-applicata-usata-solo-fini-politici-edbc365e-984c-11e9-ab34-56b2d57d687f.shtml)

### Gli Immoderati
* **07/08/2019** [I Fatti (scevri dalle Opinioni) sulla TAV](https://www.immoderati.it/2019/08/07/i-fatti-scevri-dalle-opinioni-sulla-tav/)

### Il Foglio
* **04/03/2019** [Salvate il soldato Ponti | Carlo Stagnaro](https://www.ilfoglio.it/economia/2019/03/04/news/salvate-il-soldato-ponti-241194/)

### Il Sole 24 Ore
* **12/02/2019** [Tav, i francesi: analisi di parte, considera i benefici ambientali come un costo](https://www.ilsole24ore.com/art/tav-francesi-analisi-parte-considera-benefici-ambientali-come-costo-ABnZRNTB)
* **16/02/2019** [Tav, tutte le anomalie dell’analisi costi-benefici del ministero dei Trasporti | Roberto Zucchetti](https://www.ilsole24ore.com/art/tav-tutte-anomalie-dell-analisi-costi-benefici-ministero-trasporti-ABMId9TB)
* **17/02/2019** [Tav, l’analisi costi-benefici valuta solo l’efficienza | Marco Ponti et al.](https://www.ilsole24ore.com/art/tav-l-analisi-costi-benefici-valuta-solo-l-efficienza-ABQ8uuUB)
* **20/02/2019** [Tav, ecco il documento dei 18 professori che contesta l’analisi costi-benefici](https://www.ilsole24ore.com/art/tav-ecco-documento-18-professori-che-contesta-l-analisi-costi-benefici--ABXBd4VB)
* **25/06/2019** [Tav, via libera ai bandi di gara per il lato italiano del tunnel](https://www.ilsole24ore.com/art/salvini-tav-leggera-a-me-piacciono-treni-che-corrono-ACSZfTU)
* **26/06/2019** [Tav, tutte le date chiave per il futuro dell’opera](https://www.ilsole24ore.com/art/tav-tutte-date-chiave-il-futuro-dell-opera-ACfMclU)
* **05/08/2019** [Tav Torino-Lione: la Francia approva la legge e ribadisce il suo impegno | Carlo Andrea Finotto](https://st.ilsole24ore.com/art/notizie/2019-06-18/tav-torino-lione-francia-approva-legge-e-ribadisce-suo-impegno-213811.shtml)
* **04/08/2019** [Tav Torino-Lione, gli ingegneri bocciano l’analisi costi-benefici | Carlo Andrea Finotto](https://www.ilsole24ore.com/art/tav-torino-lione-ingegneri-bocciano-analisi-scelta-sostenibile-e-strategica-ACOZLtc)
* **05/08/2019** [Tav, tra opere strategiche e analisi costi-benefici: la replica | Francesco Ramella et al.](https://www.ilsole24ore.com/art/tav-opere-strategiche-e-analisi-costi-benefici-replica-ACdu8Ld)
* **06/08/2019** [Tav sì, Tav no: ecco le sei mozioni a confronto](https://www.ilsole24ore.com/art/tav-si-tav-no-ecco-sei-mozioni-confronto-ACfebTd)


### Il Fatto Quotidiano
* **26/07/2019** [Tav, l’intervento del tecnico dell’analisi costi-benefici: “Tante bugie, dal ‘cambiamento’ son tornati a Delrio” | Francesco Ramella](https://www.ilfattoquotidiano.it/in-edicola/articoli/2019/07/26/sul-tav-tante-bugie-dal-cambiamento-son-tornati-a-delrio/5350316/)
* **15/02/2019** [Tav, l’analisi costi-benefici mette fine alla questione? La risposta è no | Massimo Famularo](https://www.ilfattoquotidiano.it/2019/02/15/tav-lanalisi-costi-benefici-mette-fine-alla-questione-la-risposta-e-no/4974392/)

### Istituto Bruno Leoni

* **16/04/2007** [BP 41. TAV: le ragioni liberali del no | Andrea Boitani et al.](http://www.brunoleoni.it/bp-41-tav-le-ragioni-liberali-del-no)
* **30/10/2014** [Tav, i conti non tornano (e non da oggi) | Francesco Ramella](http://www.brunoleoni.it/tav-i-conti-non-tornano-e-non-da-oggi)
* **22/05/2018** [Tav Torino-Lione, ecco perché lo stop è possibile | Francesco Ramella](http://www.brunoleoni.it/tav-torino-lione-ecco-perche-lo-stop-e-possibile)
* **15/03/2019** [TAV e politica delle infrastrutture | Alberto Mingardi](http://www.brunoleoni.it/tav-e-politica-delle-infrastrutture)
* **24/08/2019** [Analisi Costi-benefici: uno strumento a tutela di contribuenti e consumatori | Francesco Ramella](http://www.brunoleoni.it/tav-e-politica-delle-infrastrutture)
* **04/09/2019** [La pagliuzza “TAV” e la trave delle ferrovie | Francesco Ramella](http://www.brunoleoni.it/tav-e-politica-delle-infrastrutture)

### La Repubblica
* **08/03/2019** [Tav, società Marco Ponti firma studio Ue pro alta velocità. La replica: "Non è un'analisi costi-benefici"](https://video.repubblica.it/dossier/tav-torino-lione/tav-societa-marco-ponti-firma-studio-ue-pro-alta-velocita-la-replica-non-e-un-analisi-costi-benefici/328958/329556)

### lavoce.info 
* **08/03/2007** [TAV Torino-Lione: parlando e sparlando | Francesco Ramella](https://www.lavoce.info/archives/24138/tav-parlando-e-sparlando/)
* **12/02/2010** [TAV Torino-Lione: vale la spesa?](https://www.lavoce.info/archives/27077/tav-torino-lione-come-dimostrare-lindimostrabile/)
* **26/07/2011** [TAV Torino-Lione: Come dimostrare l'indimostrabile | Marco Ponti et al.](https://www.lavoce.info/archives/27077/tav-torino-lione-come-dimostrare-lindimostrabile/)
* **20/09/2013** [Il realismo dei francesi taglia l’alta velocità | Ivan Beltramba](https://www.lavoce.info/archives/12906/il-realismo-dei-francesi-taglia-lalta-velocita/)
* **23/09/2013** [Non morire di Tav | Andrea Boitani](https://www.lavoce.info/archives/12983/non-morire-di-tav/)
* **04/03/2014** [Renzi alla prova dei fatti sui trasporti | Francesco Ramella](https://www.lavoce.info/archives/17632/renzi-trasporti-tav/)
* **07/11/2014** [TAV e grandi opere: non è solo un problema di costi | Andrea Boitani et al.](https://www.lavoce.info/archives/31488/tav-grandi-opere-non-problema-costi/)
* **17/11/2014** [Due filosofie per privatizzare (in parte) le Ferrovie | Paolo Beria et al.](https://www.lavoce.info/archives/31488/tav-grandi-opere-non-problema-costi/)
* **07/11/2017** [Sui binari un investimento di sola andata | Marco Ponti](https://www.lavoce.info/archives/49316/sui-binari-un-investimento-sola-andata/)
* **31/07/2018** [La project review e la ferrovia Torino-Lione | Andrea Boitani](https://www.lavoce.info/archives/54463/le-project-review-e-la-torino-lione/)
* **25/01/2019** [Costi e benefici delle nuove linee ferroviarie: chi ha ragione? | Massimo Tavoni et al.](https://www.lavoce.info/archives/57218/costi-e-benefici-delle-nuove-linee-ferroviarie-chi-ha-ragione-3/)
* **29/01/2019** [Perché facciamo così l’analisi costi-benefici | Paolo Beria et al.](https://www.lavoce.info/archives/57592/la-tav-della-discordia/)
* **08/02/2019** [Guida a una corretta analisi costi-benefici | Tatiana Cini et al.](https://www.lavoce.info/archives/57446/guida-a-una-corretta-analisi-costi-benefici/)
* **15/02/2019** [La Tav della discordia](https://www.lavoce.info/archives/57592/la-tav-della-discordia/)
* **15/02/2019** [Se l’analisi della Tav parte da ipotesi arbitrarie | Percoco et al.](https://www.lavoce.info/archives/57587/se-lanalisi-della-tav-parte-da-ipotesi-arbitrarie/)
* **15/02/2019** [Quanti luoghi comuni sulle analisi costi-benefici | Claudio Virno](https://www.lavoce.info/archives/57576/quanti-luoghi-comuni-sulle-analisi-costi-benefici/)
* **18/02/2019** [Due precisazioni su accise e inquinamento | Ramella et al. vs. Percoco et al.](https://www.lavoce.info/archives/57623/due-precisazioni-su-accise-e-inquinamento/)
* **19/02/2019** [Analisi costi benefici: il vantaggio del metodo standard | Tatiana Cini et al.](https://www.lavoce.info/archives/57653/analisi-costi-benefici-e-un-vantaggio-seguire-metodologie-standard/)
* **22/02/2019** [Punti deboli e oscuri dell’analisi sulla Torino-Lione | Paolo Foietta et al.](https://www.lavoce.info/archives/57730/punti-deboli-e-oscuri-dellanalisi-sulla-torino-lione/)
* **22/02/2019** [Perché la Tav giova al mercato? | Ferdinando Monte ](https://www.lavoce.info/archives/57704/al-dibattito-sulla-tav-manca-la-visione-di-spazi-piu-ampi/)
* **26/02/2019** [Analisi Tav: a ciascuno il suo punto di vista | Paolo Beria et al.](https://www.lavoce.info/archives/57772/torino-lione-dove-sbaglia-la-contestazione-allanalisi-costi-benefici/)
* **06/03/2019** [Annullare la Tav? Cronaca di uno spreco annunciato | Roberto Camagni](https://www.lavoce.info/archives/57932/annullare-la-tav-cronaca-di-uno-spreco-annunciato/)
* **10/09/2019** [Mano leggera dell’Antitrust sulle violazioni di Ferrovie | Carlo Stagnaro](https://www.lavoce.info/archives/61035/mano-leggera-dellantitrust-sulle-violazioni-di-ferrovie/)


### Linkiesta
* **06/03/2019** [L’Europa ha già condannato a morte la Tav, ma in Italia non se n’è accorto nessuno](https://www.linkiesta.it/it/article/2019/02/13/leuropa-ha-gia-condannato-a-morte-la-tav-ma-in-italia-non-se-ne-accort/41079/)


### Scienza in Rete
* **24/03/2019** [TAV Torino-Lione: analisi costi-benefici a confronto | Fabio Pasquali](https://www.scienzainrete.it/articolo/tav-torino-lione-analisi-costi-benefici-confronto/fabio-pasquali/2019-03-24)

### Valigia Blu
* **08/12/2019** [TAV Torino-Lione: a che punto sono i lavori, i costi-benefici, il dibattito pro e contro](https://www.valigiablu.it/tav-torino-lione-lavori-costi/)






