---
title: "TAV Torino-Lione | Bibliografia"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```
## Engineering
* **12/2016** [High-Speed Rail: Opportunities and Threats](https://www.sciencedirect.com/science/article/pii/S2095809917300760)

## European Commision 
* **01/07/2008** [Guide to cost-benefit analysis of investment projects](https://ec.europa.eu/regional_policy/en/information/publications/evaluations-guidance-documents/2008/guide-to-cost-benefit-analysis-of-investment-projects)
* **08/01/2014** [Update of the Handbook on External Costs of Transport](https://ec.europa.eu/transport/sites/transport/files/handbook_on_external_costs_of_transport_2014_0.pdf)
* **12/2014** [Mediterranean Core Network Corridor Study](https://ec.europa.eu/transport/sites/transport/files/mediterranean_study_0.pdf)
* **19/12/2014** [Guide to Cost-Benefit Analysis of Investment Projects for Cohesion Policy 2014-2020](https://ec.europa.eu/regional_policy/en/information/publications/guides/2014/guide-to-cost-benefit-analysis-of-investment-projects-for-cohesion-policy-2014-2020)

## European Court of Auditors
* **26/06/2018** [A European high-speed rail network: not a reality but an ineffective patchwork](http://publications.europa.eu/webpub/eca/special-reports/high-speed-rail-19-2018/en/)

## INFRAS
* **16/12/2017** [External costs in mountain areas](https://www.alpine-region.eu/sites/default/files/uploads/publication/1029/publications/eusalp_external-costs-in-mountain-areas_final-report_fin.pdf)

## ISPRA
* **15/05/2018** [L’inventario nazionale di gas serra](http://www.isprambiente.gov.it/files2018/eventi/gas-serra/DeLauretisTrend_GHG201810284.pdf)

## Journal of Rail Transport Planning & Management
* **02/2013** [A note on high-speed rail investments and travelers’ value of time](https://www.sciencedirect.com/science/article/pii/S2210970613000188)
* **05/2015** [When to invest in high speed rail](https://www.sciencedirect.com/science/article/pii/S2210970615000037)

## Journal of Transport Geography
* **05/2015** [High Speed Rail in Britain: about time or a waste of time?](https://www.sciencedirect.com/science/article/abs/pii/S096669231200066X)

## Libri Divulgativi
* **08/2018** [The Cost-Benefit Revolution | Cass Sunstein](https://mitpress.mit.edu/books/cost-benefit-revolution?utm_source=medium&utm_medium=socical&utm_campaign=f18_trade_sunstein)
* **12/2018** [Trasporti : Conoscere per deliberare | Marco Ponti & Francesco Ramella](https://www.amazon.it/Trasporti-Conoscere-deliberare-Marco-Ponti/dp/8823846099)

## Ministère de la Transition écologique et solidaire
* **28/03/2017** [Évaluation des projets de transport](https://www.ecologique-solidaire.gouv.fr/evaluation-des-projets-transport)

## Ministero Infrastrutture e Trasporti
* **06/06/2017** [Linee guida per la valutazione degli investimenti in opere pubbliche nei settori di competenza del Ministero delle Infrastrutture e dei Trasporti](http://www.mit.gov.it/index.php/node/5272)

## Transportation Policy
* **07/2015** [When supply travels far beyond demand: Causes of oversupply in Spain's transport infrastructure](https://www.sciencedirect.com/science/article/abs/pii/S0967070X15000414)
* **02/2018** [Can high-speed rail have a transformative effect on the economy?](https://www.sciencedirect.com/science/article/abs/pii/S0967070X17301002)
* **10/2018** [Delusions of success: Costs and demand of high-speed rail in Italy and Spain](https://www.sciencedirect.com/science/article/abs/pii/S0967070X17306194)

## Transportation Research
* **10/2016** [The impact of high-speed rail investment on economic and environmental change in China: A dynamic CGE analysis](https://www.sciencedirect.com/science/article/pii/S0965856416306681?via%3Dihub)

## Transportation Research Procedia
* **10/2016** [Wider economic impacts of high-speed rail: example of agglomeration benefits assessment on Bretagne Pays de Loire high speed rail project](https://www.sciencedirect.com/science/article/pii/S2352146518300607)
* **2017** [Towards oversized high-speed rail systems? Some lessons from France and Spain](https://www.sciencedirect.com/science/article/pii/S2352146517307214)
