---
title: "Torino-Lione | Video"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

# Youtube 

* **3/03/2012** : TAV, Ne vale davvero la pena? ( [Parte 1](https://www.youtube.com/watch?v=uMUArp1_sk4&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=82&t=0s) ; [Parte 2](https://www.youtube.com/watch?v=j39NVd-vy8Y&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=85&t=0s) ; [Parte 3](https://www.youtube.com/watch?v=zcHDDcDCRD0&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=79&t=0s) )
* **14/11/2018** [TAV Torino-Lione | Ponti e Foietta a Porta a Porta](https://www.youtube.com/watch?v=VNcj9q17oqM&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=3&t=0s)
* **20/02/2019** [TAV Torino-Lione | Giuricin a LiberiOltre 1](https://www.youtube.com/watch?v=JHsgtkEcWGg&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=41&frags=pl%2Cwn)
* **08/03/2019** [TAV Torino-Lione | Ponti a Open](https://www.youtube.com/watch?v=igd2M7ZU2xk&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=2&t=0s&frags=pl%2Cwn)
* **28/03/2019** [TAV Torino-Lione | Ponti a Fatti & Misfatti](https://www.youtube.com/watch?v=2M5rboUbTRU&feature=youtu.be)
* **25/07/2019** [TAV Torino-Lione | Ponti e Giuricin a Sky Tg24 Economia](https://www.youtube.com/watch?v=H57gsZftPB8&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=9&t=0s)
* **30/07/2019** [TAV Torino-Lione | Giuricin a LiberiOltre 2](https://www.youtube.com/watch?v=Yt2txVsxIqQ&list=PL0hc3uclokfAgvPyULkWunOdBWXn7_Zjp&index=6&t=0s)
* **30/07/2019** [TAV Torino-Lione | Ramella a Unomattina](https://www.youtube.com/watch?v=zKJA0T93iV4)

#### Politecnico di Torino 
* **04/11/2011** [TAV Torino-Lione | Dibattito](https://www.youtube.com/watch?v=aQPxTRDpeto)
* **22/11/2018** [TAV Torino-Lione | Dibattito](https://www.facebook.com/Alterpolis/videos/tav-torino-lione-dibattito-al-politecnico/196793061240455/)


#### Commissione Trasporti 
* **13/02/2019** [TAV Torino-Lione | Audizione Parlamentare](https://www.youtube.com/watch?v=mQqKbHmPKT0&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=1)

#### Collegio Carlo Alberto | Fondamenti tecnici dell’analisi costi-benefici
* **28/02/2019** [ACB Torino-Lione | Introduzione di Navaretti](https://www.youtube.com/watch?v=mQqKbHmPKT0&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=1)
* **28/02/2019** [ACB Torino-Lione | Presentazione di Ponti](https://www.youtube.com/watch?v=20mKt8Kh5H0&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=2) ([Slides](https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.carloalberto.org%2Fwp-content%2Fuploads%2F2019%2F02%2FPONTI-E-RAMELLA.pdf&redir_token=3bPmy0jsoC0hWuj3ktMYh4wOBcZ8MTU2NTIyMTU4N0AxNTY1MTM1MTg3&v=20mKt8Kh5H0&event=video_description))
* **28/02/2019** [ACB Torino-Lione | Presentazione di Ramella](https://www.youtube.com/watch?v=lW6IKDl7JbM&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=3) ([Slides](https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.carloalberto.org%2Fwp-content%2Fuploads%2F2019%2F02%2FPONTI-E-RAMELLA.pdf&redir_token=3bPmy0jsoC0hWuj3ktMYh4wOBcZ8MTU2NTIyMTU4N0AxNTY1MTM1MTg3&v=20mKt8Kh5H0&event=video_description))
* **28/02/2019** [ACB Torino-Lione | Revisione di Florio](https://www.youtube.com/watch?v=VrZEl6dHqBA&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=4) ([Slides](https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.carloalberto.org%2Fwp-content%2Fuploads%2F2019%2F02%2FFLORIO.pdf&redir_token=3bPmy0jsoC0hWuj3ktMYh4wOBcZ8MTU2NTIyMTU4N0AxNTY1MTM1MTg3&v=20mKt8Kh5H0&event=video_description))
* **28/02/2019** [ACB Torino-Lione | Revisione di Boitani](https://www.youtube.com/watch?v=gLf0sQbVEyw&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=5) ([Slides](https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.carloalberto.org%2Fwp-content%2Fuploads%2F2019%2F02%2FBOITANI.pdf&redir_token=3bPmy0jsoC0hWuj3ktMYh4wOBcZ8MTU2NTIyMTU4N0AxNTY1MTM1MTg3&v=20mKt8Kh5H0&event=video_description))
* **28/02/2019** [ACB Torino-Lione | Revisione di Percoco](https://www.youtube.com/watch?v=HgznAs-7vHs&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=6)([Slides](https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.carloalberto.org%2Fwp-content%2Fuploads%2F2019%2F02%2FPERCOCO.pdf&redir_token=3bPmy0jsoC0hWuj3ktMYh4wOBcZ8MTU2NTIyMTU4N0AxNTY1MTM1MTg3&v=20mKt8Kh5H0&event=video_description))
* **28/02/2019** [ACB Torino-Lione | Dibattito](https://www.youtube.com/watch?v=qxINLeIADlw&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=7)
* **28/02/2019** [ACB Torino-Lione | Q&A](https://www.youtube.com/watch?v=nat_-8_Z9Gk&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=8)

#### Transport Research Lab | Valutare la TAV: Missione Impossibile ?
* **25/06/2019** [ACB Torino-Lione | Pasquali e Ramella](https://www.youtube.com/watch?v=nat_-8_Z9Gk&list=PL0hc3uclokfB7dobUlKmULBOrdcV1v3A9&index=8)

#### Palazzo Chigi 
* **07/03/2019** [TAV Torino-Lione | Conferenza Stampa del Presidente Conte](https://www.youtube.com/watch?v=Qvm1orfoS-I)

# Rai 

#### Agorà
* **13/02/2019** [L'ora della veritav](https://www.raiplay.it/video/2019/02/Agora-08f662e7-67fc-4a1f-ad11-281e5b366715.html)

#### Porta a Porta 
* **31/10/2018** [NO TAV](https://www.raiplay.it/video/2018/11/NO-TAV-31102018-47c00dbd-74fd-4bb8-8f72-b445d40d4dbc.html)

#### Report 
* **06/05/2019** [Dentro il tunnel](https://www.raiplay.it/video/2019/05/Dentro-il-tunnel---06052019-02262afb-604e-4413-b196-47fcfd972c2a.html)

#### Unomattina 
* **14/02/2019** [Il caso TAV](https://www.raiplay.it/video/2019/02/Tav---14022019-5ac524c9-7bd3-4c94-8a44-d96a7f2afe4e.html)
